version: 0.0
os: linux 

files:
  - source: /
    destination: /home/ec2-user/toyProject

hooks:
  ApplicationStop:
    - location: script/stop.sh
    - timeout: 90
  AfterInstall:
    - location: scripts/start.sh
    - timeout: 90