version: 0.0
os: linux 

files:
  - source: /
    destination: /home/ec2-user/toyProject

permissions:
  - object: /home/ec2-user/toyProject
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  
  - object: /home/ec2-user/toyProject
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 744
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 90
      runas: ec2-user
  AfterInstall:
    - location: scripts/start.sh
      timeout: 90
      runas: ec2-user